# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 28 Aug 2023 11:43:31 +0000
*               @ALL          1
*               @user         8
