<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ycaby
 * Date: Mon, 28 Aug 2023 11:55:28 +0000
 */

$conf['title'] = 'Kesako';
$conf['lang'] = 'fr';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox';
$conf['tpl']['mindthedark']['autoDark'] = 1;
