# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 28 Aug 2023 11:43:31 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

ycaby:$2y$10$nSzM9OJoDut2SWwxnTrf2Oj8VIV06Sjf0w/IXdIM3awji64kIpKdG:Yohann CABY:ycaby@krokinux.xyz:admin,user
